apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-alpha-quota
  namespace: dev-team-alpha
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
